#!/bin/bash
set -e
go install golang.org/x/vuln/cmd/govulncheck@latest
go install github.com/securego/gosec/v2/cmd/gosec@latest
go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
go mod tidy
go test -v ./...
go build -v ./...
govulncheck ./...
gosec ./...
golangci-lint run
