# Build golang project 
name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - name: Chechout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Bump Version
      uses: actions-ecosystem/action-bump-semver@v1
      id: bump
      with:
        current_version: latest
        level: patch

    - name: Push Version Tag
      run: |
        git push origin ${{ steps.bump.outputs.new_tag }}