name: Release new version

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    name: build, test and release
    permissions:
      issues: write
      contents: write
    strategy:
      matrix:
        go: [1.24.0]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      #- name: lint
      #  uses: golangci/golangci-lint-action@v8
      #  with:
      #    version: v2.1
      - name: build
        run: go mod tidy
      - name: test
        run: go test -v ./...
      - name: setup release
        run: |
          go install github.com/go-semantic-release/semantic-release/v2/cmd/semantic-release@v2.31.0
      - name: release
        uses: go-semantic-release/action@v1
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}