name: Release

on:
  push:
    branches:
      - main

jobs:
  build_assets:
    name: Build and Package Binaries
    runs-on: ${{ matrix.runner_os }}
    strategy:
      matrix:
        include:
          - runner_os: ubuntu-latest
            goos: linux
            goarch: amd64
            asset_ext: tar.gz
          - runner_os: windows-latest
            goos: windows
            goarch: amd64
            asset_ext: zip
          - runner_os: macos-latest
            goos: darwin
            goarch: amd64
            asset_ext: tar.gz
          
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
      - id: govulncheck
        uses: golang/govulncheck-action@v1
      - name: Build and Set Variables
        id: vars
        run: |
          ./build.sh
          BIN_NAME="${{ github.event.repository.name }}"
          if [[ "${{ matrix.goos }}" == "windows" ]]; then
            FULL_BIN_NAME="${BIN_NAME}.exe"
          else
            FULL_BIN_NAME="${BIN_NAME}"
          fi
          echo "goos=${{ matrix.goos }}" >> $GITHUB_OUTPUT
          echo "goarch=${{ matrix.goarch }}" >> $GITHUB_OUTPUT
          echo "ext=${{ matrix.asset_ext }}" >> $GITHUB_OUTPUT
          echo "bin_name=$BIN_NAME" >> $GITHUB_OUTPUT
          echo "full_bin_name=$FULL_BIN_NAME" >> $GITHUB_OUTPUT
        shell: bash
      - name: Build Binary
        run: |
          env GOOS=${{ steps.vars.outputs.goos }} GOARCH=${{ steps.vars.outputs.goarch }} go build -o ${{ steps.vars.outputs.full_bin_name }} .
      - name: Package Binary (unix)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        id: package-unix
        run: |
          ASSET_FILE="${{ steps.vars.outputs.bin_name }}_${{ steps.vars.outputs.goos }}_${{ steps.vars.outputs.goarch }}.${{ steps.vars.outputs.ext }}"
          tar -czvf "$ASSET_FILE" "${{ steps.vars.outputs.bin_name }}"
          echo "asset_file=$ASSET_FILE" >> $GITHUB_OUTPUT
      - name: Package Binary (windows)
        if: runner.os == 'Windows'
        id: package-windows
        run: |
          ASSET_FILE="${{ steps.vars.outputs.bin_name }}_${{ steps.vars.outputs.goos }}_${{ steps.vars.outputs.goarch }}.${{ steps.vars.outputs.ext }}"
          7z a "$ASSET_FILE" "${{ steps.vars.outputs.full_bin_name }}"
          echo "asset_file=$ASSET_FILE" >> $GITHUB_OUTPUT
        shell: bash
      - name: Upload Artifact (unix)
        id: upload-unix
        if: runner.os == 'Linux' || runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package-unix.outputs.asset_file }}
          path: ${{ steps.package-unix.outputs.asset_file }}
      - name: Upload Artifact Windows
        id: upload-windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package-windows.outputs.asset_file }}
          path: ${{ steps.package-windows.outputs.asset_file }}

  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build_assets
    permissions:
      contents: write 
      actions: write
    outputs:
      new_tag: ${{ steps.tagger.outputs.new_tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Calculate and Create Tag
        id: tagger
        uses: anothrNick/github-tag-action@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          DRY_RUN: true
          DEFAULT_BUMP: patch
      - name: Download all assets
        uses: actions/download-artifact@v5
        with:
          path: assets
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tagger.outputs.new_tag }}
          generate_release_notes: true 
          files: assets/**/*