name: 01 - Build and Tag

on:
  push:
    branches:
      - main
      
jobs:
  tagging:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    outputs:
      new_tag: ${{ steps.tagger.outputs.new_tag }}
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          
      - name: Calculate and Create Tag
        id: tagger
        uses: anothrNick/github-tag-action@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Log New Tag
        if: steps.tagger.outputs.new_tag != ''
        run: |
        echo "Generated Tag: ${{ steps.tagger.outputs.new_tag }}"
        
      - name: Trigger Release Workflow
        if: steps.tagger.outputs.new_tag != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const newTag = "${{ steps.tagger.outputs.new_tag }}";
            
            console.log(`Dispatching release workflow for tag: ${newTag}`);
            
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'release.yml',
              ref: context.ref,
              client_payload: {
                tag: newTag
              }
            });