name: 01 - Build and Tag

on:
  push:
    branches:
      - main
      
jobs:
  tagging:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    
    outputs:
      new_tag: ${{ steps.tagger.outputs.new_tag }}
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          
      - name: Calculate and Create Tag
        id: tagger
        uses: anothrNick/github-tag-action@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          
      - name: Log New Tag
        if: steps.tagger.outputs.new_tag != ''
        run: |
            echo 'Generated Tag: ${{ steps.tagger.outputs.new_tag }}'