name: 01 - Build and Tag

on:
  push:
    branches:
      - main
      
jobs:
  tagging:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create and push the new tag
    
    outputs:
      new_tag: ${{ steps.tagger.outputs.new_tag }}
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # IMPORTANT: Needs full history to calculate the version
          
      - name: Calculate and Create Tag
        id: tagger
        uses: anothrNick/github-tag-action@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # WITH_V: true # adds 'v' prefix if desired
          
      - name: Log New Tag
        if: steps.tagger.outputs.new_tag != ''
        run: echo "Generated Tag: ${{ steps.tagger.outputs.new_tag }}"
        
      - name: Trigger Release Workflow
        if: steps.tagger.outputs.new_tag != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # 🟢 CORRECTION: Use the pipe (|) for cleaner multi-line script syntax
          script: |
            const newTag = "${{ steps.tagger.outputs.new_tag }}";
            
            console.log(`Dispatching release workflow for tag: ${newTag}`);
            
            // This triggers the second workflow (02-release.yml)
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'release.yml',
              ref: context.ref,
              client_payload: {
                tag: newTag
              }
            });